## General
spring:
   application:
    name: fliperama
   datasource:
      url: jdbc:postgresql://localhost:5432/fliperama
      username: postgres
      password: admin
   jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
server:
   port: 8080
   contextPath: /fliperama