## General
spring:
   application:
    name: fliperama
   datasource:
      url: jdbc:mysql://localhost:3306/fliperama
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      useSSL: false
   jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
server:
   port: 8080
   contextPath: /fliperama